#' Check Aggregation Consistency for GTAP Data
#'
#' Converts the text mapping aggregation template file to a HAR format
#' and runs a consistency check.
#'
#' @param mapfile Gempack text file with aggregation template,
#'     generated by gtapshape.
#' @param setfile HAR file with GTAP sets, including the subnational
#'     bounds, also generated by gtapshape.
#'
#' @details
#' The function performs the following steps:
#' 1. Calls `txt2map()` to convert the text mapping file to HAR format.
#' 2. Creates an 'aggcheck.cmf' configuration file specifying input and output files.
#' 3. Executes the 'aggcheck' system command to check aggregation consistency.
#' 4. Removes the temporary 'aggcheck.har' file.
#'
#' Input files:
#' - mapfile: Text file containing aggregation mappings (converted to gmap.har)
#' - setfile: Sets for disaggregated GTAP data
#'
#' Output files:
#' - gmap.har: Set mapping for aggregating data (created by txt2map)
#' - aggcheck.har: Temporary file created by aggcheck command (removed after execution)
#'
#' @return This function does not return a value. It performs consistency checks and creates temporary files.
#'
#' @export
#'
#' @seealso
#' \code{\link{maptext2har}}
#'
aggcheck <- function(mapfile,setfile){
    maptext2har(mapfile)
    write_cmf(cmf_filename = "aggcheck.cmf",
          input_files = list(DSETS=setfile,
                             ASETS="gmap.har"),
          output_files = list(checkmap="aggcheck.har"),
          out_dir=getwd()
          )
    run_gtap_program(program="./gempack/aggcheck", cmf="aggcheck.cmf")
    file.remove("aggcheck.har")
    }
