#' Create Aggregated Data and Parameters for GTAP
#'
#' This function performs a series of operations to create aggregated data and parameters
#' for GTAP (Global Trade Analysis Project) modeling. It aggregates data, processes land use
#' parameters, generates a GTAP view, and packages the resulting files.
#'
#' @param mapfile Gempack text file with aggregation template,
#'     generated by gtapshape.
#' @param setfile HAR file with GTAP sets, including the subnational
#'     bounds, also generated by gtapshape.
#' @param datfile HAR file with GTAP data, including the land use dat
#'     by subnational bounds, also generated by gtapshape.
#' @param stdprm HAR file with parameters for the standard GTAP
#'     database..
#' @param dir Character string. Directory where output files will be
#'     saved.
#'
#' @details
#' The function performs the following steps:
#' 1. Aggregates data using `aggdat()`.
#' 2. Processes land use parameters using `lusepar()`.
#' 3. Generates a GTAP view using `gtapview()`.
#' 4. Creates a zip file containing input files.
#' 5. Removes temporary files.
#'
#' @return This function does not return a value. It creates output files in the specified directory.
#'
#' @export
#'
#' @examples
#' \dontrun{
#' createdat("path/to/mapfile", "path/to/setfile", "path/to/datfile",
#'           "path/to/stdprm", "output_directory")
#' }
#'
#' @seealso
#' \code{\link{aggdat}}, \code{\link{lusepar}}, \code{\link{gtapview}}
#'
#' @importFrom utils zip
createdat <- function(mapfile, setfile, datfile, stdprm, dir){
    ## Data aggregation step, to regions, sectors and endowment
    ## aggregates specified in mapfile:
    aggdat(mapfile, setfile, datfile, dir)
    ## Aggregates parameters of the GTAP database.
    lusepar(mapfile, setfile, datfile, stdprm, dir)
    gtapview(dir)
    inputfiles <- c("aggcheck.cmf","aggdat.cmf","aggpar.cmf",
                    "lusepar.cmf","gtapview.cmf","gmap.har")
    zip(zipfile=paste("./",dir,"/inputs.zip",sep=""),files=inputfiles)
    file.remove(c(inputfiles,"gmap.sti","gmap.log"))
    }
