#' Process Land Use Parameters for GTAP
#'
#' Aggregates parameters of the GTAP database.
#'
#' @param mapfile Gempack text file with aggregation template,
#'     generated by gtapshape.
#' @param setfile HAR file with GTAP sets, including the subnational
#'     bounds, also generated by gtapshape.
#' @param datfile HAR file with GTAP data, including the land use dat
#'     by subnational bounds, also generated by gtapshape.
#' @param stdprm HAR file with parameters for the standard GTAP
#'     database..
#' @param dir Character string. Directory where output files will be
#'     saved.
#'
#' @details
#' The function performs the following steps:
#' 1. Calls `aggpar()` to aggregate parameters.
#' 2. Creates a 'lusepar.cmf' configuration file specifying input and output files.
#' 3. Executes the 'lusepar' system command to process land use parameters.
#' 4. Removes the temporary 'aggpar.har' file.
#'
#' @return This function does not return a value. It creates and modifies files in the specified directory.
#'
#' @export
#'
#' @examples
#' \dontrun{
#' lusepar("path/to/mapfile", "path/to/setfile", "path/to/datfile",
#'         "path/to/stdprm", "output_directory")
#' }
#'
#' @seealso
#' \code{\link{aggpar}}
#'
lusepar <- function(mapfile,setfile,datfile,stdprm,dir){
    aggpar(mapfile,setfile,datfile,stdprm,dir)
        write_cmf(
        cmf_filename= "lusepar.cmf",
        input_files = list(
            GTAPSETS = file.path( getwd(), dir, "sets.har"),
            ALLPARAM = file.path( getwd(), dir, "aggpar.har")
        ),
        output_files = list(
            NEWPARM = file.path( getwd(), dir, "default.prm")
        ),
        out_dir = getwd()
    )
    run_gtap_program(program="./gempack/lusepar", cmf="lusepar.cmf")
    file.remove(paste("./", dir,"/aggpar.har",sep=""))
     }

